version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Uzumakiforall1234!"
    ports:
      - "1433:1433"
    networks:
      backend:
        aliases:
          - dbcontainer

  officegamezone:
    image: ${DOCKER_REGISTRY-}officegamezone
    build:
      context: .
      dockerfile: OfficeGameZone/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      backend:

networks:
  backend:
    driver: bridge
